begin;

create table if not exists public.flashcard_sets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  cover_image text,
  created_at timestamptz default now()
);

alter table public.flashcards
  add column if not exists set_id uuid references public.flashcard_sets(id) on delete cascade;

insert into public.flashcard_sets (id, owner_id, title, description)
select gen_random_uuid(), owner_id, 'Imported Cards', 'Autogenerated set for existing flashcards.'
from public.flashcards f
where f.set_id is null
  and not exists (
    select 1 from public.flashcard_sets s
    where s.owner_id = f.owner_id and s.title = 'Imported Cards'
  )
group by owner_id;

update public.flashcards f
set set_id = (
  select s.id from public.flashcard_sets s
  where s.owner_id = f.owner_id
  order by s.created_at asc
  limit 1
)
where f.set_id is null;

alter table public.flashcards
  alter column set_id set not null;

drop index if exists flashcards_owner_created_idx;
create index if not exists flashcards_set_created_idx on public.flashcards (set_id, created_at desc);

alter table public.flashcard_sets enable row level security;
alter table public.flashcards enable row level security;

drop policy if exists "flashcard_sets_select_own" on public.flashcard_sets;
create policy "flashcard_sets_select_own" on public.flashcard_sets
  for select using (owner_id = auth.uid());

drop policy if exists "flashcard_sets_insert_own" on public.flashcard_sets;
create policy "flashcard_sets_insert_own" on public.flashcard_sets
  for insert with check (owner_id = auth.uid());

drop policy if exists "flashcard_sets_update_own" on public.flashcard_sets;
create policy "flashcard_sets_update_own" on public.flashcard_sets
  for update using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists "flashcard_sets_delete_own" on public.flashcard_sets;
create policy "flashcard_sets_delete_own" on public.flashcard_sets
  for delete using (owner_id = auth.uid());

drop policy if exists "flashcards_select_own" on public.flashcards;
create policy "flashcards_select_own" on public.flashcards
  for select using (owner_id = auth.uid());

drop policy if exists "flashcards_insert_own" on public.flashcards;
create policy "flashcards_insert_own" on public.flashcards
  for insert with check (
    owner_id = auth.uid()
    and exists (
      select 1 from public.flashcard_sets s
      where s.id = set_id and s.owner_id = auth.uid()
    )
  );

drop policy if exists "flashcards_update_own" on public.flashcards;
create policy "flashcards_update_own" on public.flashcards
  for update using (
    owner_id = auth.uid()
    and exists (
      select 1 from public.flashcard_sets s
      where s.id = set_id and s.owner_id = auth.uid()
    )
  ) with check (
    owner_id = auth.uid()
    and exists (
      select 1 from public.flashcard_sets s
      where s.id = set_id and s.owner_id = auth.uid()
    )
  );

drop policy if exists "flashcards_delete_own" on public.flashcards;
create policy "flashcards_delete_own" on public.flashcards
  for delete using (
    owner_id = auth.uid()
    and exists (
      select 1 from public.flashcard_sets s
      where s.id = set_id and s.owner_id = auth.uid()
    )
  );

commit;
