import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check auth session on the server to render proper nav
  let isSignedIn = false;
  try {
    const supabase = createServerComponentClient({ cookies });
    const {
      data: { session },
    } = await supabase.auth.getSession();
    isSignedIn = !!session;
  } catch {}
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-40 w-full border-b border-slate-200/70 bg-white/70 backdrop-blur supports-[backdrop-filter]:bg-white/60">
          <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
            <a href="/" className="font-semibold tracking-tight text-slate-900">
              LevantTalk
            </a>
            <nav className="flex items-center gap-3 text-sm">
              {isSignedIn ? (
                <a
                  href="/dashboard"
                  className="px-3 py-1.5 rounded-md bg-slate-900 text-white hover:bg-slate-800"
                >
                  Dashboard
                </a>
              ) : (
                <>
                  <a
                    href="/login"
                    className="px-3 py-1.5 rounded-md text-slate-700 hover:bg-slate-100"
                  >
                    Login
                  </a>
                  <a
                    href="/signup"
                    className="px-3 py-1.5 rounded-md bg-indigo-600 text-white hover:bg-indigo-500"
                  >
                    Sign Up
                  </a>
                </>
              )}
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
